Add: Currency API Client
magnet-cl/django-magnet-data pull request #1
Opened 2022-07-06 03:08 UTC by imunizaga

* Include an API client to obtain month values
* Include a currency client.
* Include model and cache storage to improve performance

2022-10-12 22:41 UTC, jslopez requested changes

2022-10-12 22:41 UTC, jslopez commented on magnet_data/currencies/client.py
> +    if not isinstance(month, str) and month < 10:
@imunizaga  Sería mejor evaluar `isinstance` de `int` considerando la firma del método?

2022-10-12 22:41 UTC, jslopez commented on magnet_data/currencies/currency_pair.py
> +        return currency_value.value
@imunizaga ¿está bien que acá no se haga cast a `Decimal` como cuando se obtiene el valor desde el cache?

2022-10-12 22:41 UTC, jslopez commented on magnet_data/currencies/currency_pair.py
> +        Return the current value of base_currency as counter_currency
@imunizaga Complementar docstring para entender la diferencia con el método anterior.

2022-10-12 22:41 UTC, jslopez commented on magnet_data/currencies/currency_pair.py
> +        return currency_value.value
Parece que está bien sin el cast porque el field se definió como DecimalField.

2022-10-13 23:08 UTC, nstuardod commented
Ya que se está usando typing para definir los tipos de los parámetros, definir también los tipos de retorno.

2022-10-14 18:48 UTC, munimagnet commented on magnet_data/currencies/client.py
> +    if not isinstance(month, str) and month < 10:
Creo que es mejor borrarlo, si alguien lo llama como string está fallando con la firma.

2022-10-17 17:29 UTC, jslopez approved these changes

2022-10-17 17:40 UTC, merged